---
title: "tree_graphs5"
output: html_document
date: "2022-11-26"
---

```{r setup, include=FALSE}
# knitr::opts_knit$set(root.dir = "C:/Users/ignac/OneDrive/Escritorio/TP Final EEA/tp2EEA")
```


```{r}

library(rpart)
library(rattle)
library(tidyverse)
library(plotly)

```

Data generating Process


$$ Z = f(x,y) + \epsilon = \sqrt{(x-9)^2 + (y-9)^2} + \epsilon \text{ con } \epsilon \sim \mathcal{N}(0,0.5) $$



```{r}
#Vamos a crear un dataset sintético y graficarlo en 3D
set.seed(911)

n = 100

dtrain <- data.frame(x = runif(n,4.5,13.5),y = runif(n,4.5,13.5))
noise <- rnorm(n, mean=0, sd=0.5)
dtrain <- dtrain %>% mutate(z = sqrt((x-9)**2+(y-9)**2)+noise)


#Visualización del dataset sintético
plot_ly(dtrain, x = ~x, y = ~y, z = ~z) %>%
  add_markers(size = 1,color = I("lightblue"))

```





```{r}

ggplot(dtrain, aes(x, y))+
  geom_point(color="orange")+
  theme_light()

```


 $ Y = f(x) +\epsilon =  \sqrt{(x_1 - 9)^2 + (x_2 - 9)^2} + \epsilon$

```{r}

tree <- rpart(z ~ y + x, data = dtrain, method = "anova",maxdepth = 3, minsplit = 1, minbucket = 1, cp = 0)
fancyRpartPlot(tree, digits=3)

rpart.plot::prp(tree, digits=2)

prp(tree)
```


El árbol minimiza esta función. 

$ SSE_{s^*}(t) = \min_{s} SSE(t_L) + SSE(t_D) = \min_{s} \sum_{i=1}^{N}{\xi_{i}}$




```{r}


fitted.values <- predict(tree, newdata = dtrain)

frame <- tree$frame
nodevec <- as.numeric(row.names(frame[frame$var == "<leaf>",])) #esto genera un vector con los números de nodos terminales
path.list <- path.rpart(tree, nodes = nodevec) #genera una lista en la cual cada elemento indica el camino a un nodo

rect_info <- NULL
for(path in path.list){
  path <- setdiff(path,"root")
  min.x = min(dtrain$x)
  max.x = max(dtrain$x)
  min.y = min(dtrain$y)
  max.y = max(dtrain$y)
  for(split in path){
    s <- unlist(str_split(split,"< |>="))
    var <- s[1]
    cutoff <- as.numeric(s[2])
    is.less <- str_detect(split,"< ")
    if(var == "x"){
      if(is.less == TRUE){
        max.x <- cutoff
      } else {
        min.x <- cutoff
      }
    } else {
      if(is.less == TRUE){
        max.y <- cutoff 
      } else {
        min.y <- cutoff
      }
    }
  }
  rect_info <- rbind(rect_info,data.frame(xmin = min.x, xmax = max.x, ymin = min.y, ymax = max.y))
}


dtrain <- dtrain %>% 
  mutate(fitted.values = round(fitted.values,1))

label_points <- dtrain %>%
  group_by(fitted.values) %>%
  summarise(x = median(x), y = median (y))

ggplot() +
  geom_rect(data = rect_info,aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),colour = "grey50", fill = "white") +
  geom_point(data = dtrain,aes(x = x, y = y, color = fitted.values)) +
  geom_label(data = label_points,aes(x = x, y = y, label = fitted.values, color=fitted.values)) +
  labs(color="Valor ajustado") +
  theme_light()

```


